name: Run tests and upload results
on:
  workflow_dispatch:

jobs:
    test:
      env:
       PROJECT_DIR: src/Railflow.NUnit.TestRail.Reporter.Example/Example/
       PROJECT_FILE: ${{env.PROJECT_DIR}}Example.csproj
       TEST_FILE: ${{env.PROJECT_DIR}}/TestResults/TestResult.xml
      
      runs-on: windows-latest
    
      steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: dotnet test ${{env.PROJECT_DIR}}Example.csproj
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
         path: ${{TEST_FILE}}
