name: Run tests and upload results
on:
  workflow_dispatch:

jobs:
    test:
      env:
       PROJECT_DIR: src/Railflow.NUnit.TestRail.Reporter.Example/Example
      
      runs-on: windows-latest
      
      steps:

      - uses: actions/checkout@v2
      
      - name: Build, restore packages and run tests
        run: dotnet test ${{env.PROJECT_DIR}}/Example.csproj
      
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
         name: Test results
         path: ${{env.PROJECT_DIR}}/TestResults/TestResult.xml
